# Generated by Django 5.0 on 2026-09-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='movie',
        ),
    ]
