# Generated by Django 5.0 on 2026-09-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_report_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.review'),
            preserve_default=False,
        ),
    ]
